[{"count": 0, "tags": [], "bug_id": 2318, "attachment_id": null, "id": 3251, "time": "2001-06-25T15:37:36Z", "creator": "galnares@us.ibm.com", "creation_time": "2001-06-25T15:37:36Z", "is_private": false, "text": "xerces-j 1.4.1 outputs the following (incorrect) error when validating a schema \ninstance against the DTD for schemas:\n\n[Error] idNotUnique.xsd:19:56: Attribute value \"bad01\" of type ID must be a \nname.\n\nThe value \"bad01\" is a valid 'name'.\n\nxerces-j 1.4.0 outputs (correctly) the following:\n\n[Error] idNotUnique.xsd:19:56: Attribute value \"bad01\" of type ID must be \nunique within the document.\n\nschema 'idNotUnique':\n\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!DOCTYPE schema SYSTEM \"XMLSchema.dtd\">\n<schema xmlns=\"http://www.w3.org/2001/XMLSchema\">\n\n\t<annotation>\n\t\t<documentation>\n\t\t\tids with duplicate values.\n\t\t</documentation>\n\t</annotation>\n\n\t<complexType name=\"ComplexTypeA\">\n\t\t<sequence>\n\t\t\t<element id=\"bad01\" name=\"ElementA1\" type=\"integer\"/>\n\t\t</sequence>\n\t</complexType>\n\n\t<complexType name=\"ComplexTypeB\">\n\t\t<sequence>\n\t\t\t<element id=\"bad01\" name=\"ElementB1\" type=\"string\"/>\n\t\t</sequence>\n\t</complexType>\n\n</schema>"}, {"count": 1, "tags": [], "bug_id": 2318, "text": "corrected the error message.", "id": 3422, "time": "2001-07-05T07:54:50Z", "creator": "sandygao@ca.ibm.com", "creation_time": "2001-07-05T07:54:50Z", "is_private": false, "attachment_id": null}]