[{"count": 0, "tags": [], "text": "I get this error when I shutdown and restart Tomcat(standalone).\r\nI have configured tomcat to run on port 80.\r\nWhen I run netstat to see the activity,after shutdown, it says listening on port 80.\r\nI double click the 'bat' files to both start and shut tomcat.\r\n\r\nThis is the error, when I try to restart tomcat after a shutdown:\r\n\r\nFATAL:java.net.BindException: Address in use: bind\r\njava.net.BindException: Address in use: bind\r\n        at java.net.PlainSocketImpl.socketBind(Native Method)\r\n        at java.net.PlainSocketImpl.bind(PlainSocketImpl.java:390)\r\n        at java.net.ServerSocket.<init>(ServerSocket.java:173)\r\n        at java.net.ServerSocket.<init>(ServerSocket.java:124)\r\n        at org.apache.tomcat.net.DefaultServerSocketFactory.createSocket(Default\r\nServerSocketFactory.java:97)\r\n        at org.apache.tomcat.service.SimpleTcpEndpoint.startEndpoint(SimpleTcpEn\r\ndpoint.java:186)\r\n        at org.apache.tomcat.service.SimpleTcpConnector.start(SimpleTcpConnector\r\n.java:142)\r\n        at org.apache.tomcat.core.ContextManager.start(ContextManager.java, Comp\r\niled Code)\r\n        at org.apache.tomcat.startup.Tomcat.execute(Tomcat.java:157)\r\n        at org.apache.tomcat.startup.Tomcat.main(Tomcat.java:163)", "attachment_id": null, "id": 225, "creation_time": "2000-11-16T15:37:56Z", "time": "2000-11-16T15:37:56Z", "creator": "dev@tomcat.apache.org", "bug_id": 247, "is_private": false}, {"count": 1, "tags": [], "bug_id": 247, "attachment_id": null, "id": 1122, "time": "2001-03-09T12:49:58Z", "creator": "marc.saegesser@apropos.com", "creation_time": "2001-03-09T12:49:58Z", "is_private": false, "text": "Tomcat wasn't really shutdown.  This works fine in Tomcat 3.2.x."}]