[{"count": 0, "tags": [], "bug_id": 28905, "attachment_id": null, "id": 57210, "time": "2004-05-11T17:26:55Z", "creator": "George.Lindholm@ubc.ca", "creation_time": "2004-05-11T17:26:55Z", "is_private": false, "text": "My stdout log file keeps filling up with:\n\nMay 11, 2004 5:33:21 AM org.apache.jk.common.ChannelSocket processConnection\nINFO: connection timeout reached\n\nThey may be useful while debugging, but in a production environment these\nmessages just hide real problems logged to stdout.\n\nApache 2.0.49.\n\n   George"}, {"count": 1, "tags": [], "bug_id": 28905, "attachment_id": null, "id": 57212, "time": "2004-05-11T17:51:36Z", "creator": "remm@apache.org", "creation_time": "2004-05-11T17:51:36Z", "is_private": false, "text": "I think the answer is that you should upgrade to a very new JK, which includes\nkeepalive support. I think the report will be invalid as soon as JK 1.2.6 is out."}, {"count": 2, "tags": [], "bug_id": 28905, "text": "I'm using 1.4.2_04.\n\n\nThe problem is actually caused by the connectionTimeout value set in\nthe Connector definition (not quite intuative, but that's what debuggers\nare there for).\n\nI'm setting it to connectionTimeout=\"0\"", "id": 57232, "time": "2004-05-11T21:57:30Z", "creator": "George.Lindholm@ubc.ca", "creation_time": "2004-05-11T21:57:30Z", "is_private": false, "attachment_id": null}]