[{"count": 0, "tags": [], "text": "We have an application where poi reads in an excel file using version 2.5.1 \nfinal. Everything works fine (except for the known bugs like comments).\nWhen we try to read in the same excel file with auto filter set to true, poi \nthrows an unknownRecordFormat exception.\nThis still worked in the previous version we were testing with (poi v2.0 Final)", "is_private": false, "id": 62522, "creator": "bart.boogaerts@realsoftware.be", "time": "2004-08-26T09:44:39Z", "bug_id": 30861, "creation_time": "2004-08-26T09:44:39Z", "attachment_id": null}, {"count": 1, "attachment_id": null, "creator": "avik@apache.org", "is_private": false, "id": 62525, "time": "2004-08-26T10:00:48Z", "bug_id": 30861, "creation_time": "2004-08-26T10:00:48Z", "tags": [], "text": "Could you possibly attach the file?"}, {"count": 2, "tags": [], "bug_id": 30861, "text": "Created attachment 12535\ntemplate file with auto filter on", "id": 62527, "time": "2004-08-26T10:11:25Z", "creator": "bart.boogaerts@realsoftware.be", "creation_time": "2004-08-26T10:11:25Z", "is_private": false, "attachment_id": 12535}, {"count": 3, "attachment_id": null, "creator": "glens@apache.org", "text": "This should be fixed with the patch that I applied for 27929.  Checkout of HEAD\nand give it a shot.", "id": 63795, "time": "2004-09-19T02:30:24Z", "bug_id": 30861, "creation_time": "2004-09-19T02:30:24Z", "tags": [], "is_private": false}, {"count": 4, "attachment_id": 12535, "creator": "y-kanda@dgic.co.jp", "text": "Comment on attachment 12535\ntemplate file with auto filter on\n\n1", "id": 71192, "time": "2005-02-18T16:54:49Z", "bug_id": 30861, "creation_time": "2005-02-18T16:54:49Z", "tags": [], "is_private": false}]