[{"count": 0, "tags": [], "text": "When we try to do the following in a directory that contains a locked file, the\ncopy fails before the end of the whole copy even if I have the attribute\nfailonerror set to \"no\".\n\n<copy failonerror=\"no\" todir=\"test\">\n  <fileset dir=\"C:\\Documents and Settings\\User\\Application\nData\\Thunderbird\\Profiles\">\n    <include name=\"**/*\" />\n   </fileset>\n</copy>\n\nIf Mozilla Thunderbird is opened, there is a locked file in the profile\ndirectory (parent.lock).", "attachment_id": null, "bug_id": 38175, "id": 84329, "time": "2006-01-08T01:46:40Z", "creator": "legege@legege.com", "creation_time": "2006-01-08T01:46:40Z", "is_private": false}, {"count": 1, "tags": [], "text": "Created attachment 17361\nProposed patch\n\nThrow the BuildException only if the failonerror is true.", "attachment_id": 17361, "bug_id": 38175, "id": 84330, "time": "2006-01-08T01:52:26Z", "creator": "legege@legege.com", "creation_time": "2006-01-08T01:52:26Z", "is_private": false}, {"count": 2, "tags": [], "creator": "mbenson@apache.org", "attachment_id": null, "id": 84373, "time": "2006-01-09T16:12:41Z", "bug_id": 38175, "creation_time": "2006-01-09T16:12:41Z", "is_private": false, "text": "(slightly modified) patch applied in SVN HEAD; thanks!"}, {"count": 3, "attachment_id": null, "bug_id": 38175, "text": "I see in the trunk that there is a new doResourceOperations() method very\nsimilar to doFileOperations(). I think, but I'm not sure, that there should be\nthe same fix for this method. Anyone can confirm this?", "id": 84398, "time": "2006-01-09T17:53:15Z", "creator": "legege@legege.com", "creation_time": "2006-01-09T17:53:15Z", "tags": [], "is_private": false}, {"count": 4, "tags": [], "bug_id": 38175, "is_private": false, "text": "You are correct; done.  :)  Thanks for the catch!", "id": 84403, "time": "2006-01-09T18:22:21Z", "creator": "mbenson@apache.org", "creation_time": "2006-01-09T18:22:21Z", "attachment_id": null}]