[{"count": 0, "tags": [], "bug_id": 48332, "text": "Created attachment 24661\nBiffViewer output\n\nI have an Excel file that POI is not able to read.  MS Excel and OpenOffice can read it.  Attached is the BiffViewer output.  The Excel was created by another process using SoftArtisans OfficeWriter for Excel 7.0.0.1642 (http://officewriter.softartisans.com).\n\nI really need to read this file via POI.  Please help.", "id": 132589, "time": "2009-12-02T11:50:55Z", "creator": "vdhanda@epistemic.com", "creation_time": "2009-12-02T11:50:55Z", "is_private": false, "attachment_id": 24661}, {"count": 1, "attachment_id": 24662, "creator": "vdhanda@epistemic.com", "is_private": false, "id": 132590, "time": "2009-12-02T11:52:28Z", "bug_id": 48332, "creation_time": "2009-12-02T11:52:28Z", "tags": [], "text": "Created attachment 24662\nThe Excel"}, {"count": 2, "attachment_id": null, "creator": "josh@apache.org", "is_private": false, "id": 132591, "time": "2009-12-02T11:55:06Z", "bug_id": 48332, "creation_time": "2009-12-02T11:55:06Z", "tags": [], "text": "Can you please attach the stack-trace of your error?  Also, can you investigate whether re-saving the file with Excel allows POI to read it?"}, {"count": 3, "tags": [], "creator": "vdhanda@epistemic.com", "attachment_id": null, "text": "Hello Josh,\n\nYes, if I open and save the file in Excel and/or OpenOffice, the POI can read it.  \n\nThe stack trace from BiffViewer is at the bottom of the BiffViewer output.  Here's the stack trace from my application.\n\nException in thread \"main\" org.apache.poi.hssf.record.RecordFormatException: Unable to construct record instance\n\tat org.apache.poi.hssf.record.RecordFactory$ReflectionRecordCreator.create(RecordFactory.java:64)\n\tat org.apache.poi.hssf.record.RecordFactory.createSingleRecord(RecordFactory.java:263)\n\tat org.apache.poi.hssf.record.RecordFactoryInputStream.readNextRecord(RecordFactoryInputStream.java:270)\n\tat org.apache.poi.hssf.record.RecordFactoryInputStream.nextRecord(RecordFactoryInputStream.java:236)\n\tat org.apache.poi.hssf.record.RecordFactory.createRecords(RecordFactory.java:377)\n\tat org.apache.poi.hssf.usermodel.HSSFWorkbook.<init>(HSSFWorkbook.java:275)\n\tat org.apache.poi.hssf.usermodel.HSSFWorkbook.<init>(HSSFWorkbook.java:200)\n\tat org.apache.poi.hssf.usermodel.HSSFWorkbook.<init>(HSSFWorkbook.java:182)\n\tat com.epistemic.http.ExcelHandler.handleResponseBody(ExcelHandler.java:126)\n\tat com.aexp.pl.Tester.main(Tester.java:17)\nCaused by: java.lang.RuntimeException: Unusual record size remaining=(0)\n\tat org.apache.poi.hssf.record.ColumnInfoRecord.<init>(ColumnInfoRecord.java:72)\n\tat sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)\n\tat sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)\n\tat sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)\n\tat java.lang.reflect.Constructor.newInstance(Constructor.java:513)\n\tat org.apache.poi.hssf.record.RecordFactory$ReflectionRecordCreator.create(RecordFactory.java:56)\n\t... 9 more", "id": 132592, "time": "2009-12-02T11:59:36Z", "bug_id": 48332, "creation_time": "2009-12-02T11:59:36Z", "is_private": false}, {"count": 4, "tags": [], "bug_id": 48332, "text": "Fixed in svn r886311\n\njunits added", "id": 132595, "time": "2009-12-02T13:30:14Z", "creator": "josh@apache.org", "creation_time": "2009-12-02T13:30:14Z", "is_private": false, "attachment_id": null}]