[{"count": 0, "tags": [], "bug_id": 48438, "attachment_id": 24753, "text": "Created attachment 24753\n/webapps/examples/jsp/tagplugin/if.jsp\n\nSteps to reproduce:\n1. Download and install 6.0.21 release candidate \"try2\"\n2. Replace /webapps/examples/jsp/tagplugin/if.jsp with the file attacted to this bug report. It has a few lines added to reproduce bug 48112.\n3. Run  catalina start -security\n4. Access http://localhost:8080/examples/jsp/tagplugin/if.jsp\n5. Observe Error 500 page with java.security.AccessControlException\n\njava.security.AccessControlException: access denied (java.lang.RuntimePermission accessClassInPackage.org.apache.jasper.security)\n\tjava.security.AccessControlContext.checkPermission(Unknown Source)\n\tjava.security.AccessController.checkPermission(Unknown Source)\n\tjava.lang.SecurityManager.checkPermission(Unknown Source)\n\tjava.lang.SecurityManager.checkPackageAccess(Unknown Source)\n\tsun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)\n\tjava.lang.ClassLoader.loadClass(Unknown Source)\n\tjava.lang.ClassLoader.loadClass(Unknown Source)\n\tjava.lang.ClassLoader.loadClassInternal(Unknown Source)\norg.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction(ProtectedFunctionMapper.java:145)\n\torg.apache.jsp.jsp.tagplugin.if_jsp.<clinit>(if_jsp.java:13)\n\nThe full stack trace will be in an attachment.\n\n6. If run without Security manager, the error report as described in bug 48112 is observed, that is\n(..)\norg.apache.el.parser.ParseException: Encountered \" <ILLEGAL_CHARACTER> \"\\' \"\"\nat line 1, column 11.\n(..)\n\n5. is the unexpected result, 6. is the expected result", "id": 133085, "time": "2009-12-23T05:26:17Z", "creator": "knst.kolinko@gmail.com", "creation_time": "2009-12-23T05:26:17Z", "is_private": false}, {"count": 1, "tags": [], "bug_id": 48438, "attachment_id": 24754, "text": "Created attachment 24754\nlocalhost.2009-12-23.log that contains the full stack trace", "id": 133086, "time": "2009-12-23T05:28:43Z", "creator": "knst.kolinko@gmail.com", "creation_time": "2009-12-23T05:28:43Z", "is_private": false}, {"count": 2, "tags": [], "creator": "knst.kolinko@gmail.com", "text": "Retrying to reproduce this with\n\\webapps\\examples\\jsp\\jsp2\\el\\basic-arithmetic.jsp\n\nIf I add the following four lines to the end of the file:\n    48112:\n    <%@ taglib uri=\"http://java.sun.com/jsp/jstl/core\" prefix=\"c\" %>\n    <%@ taglib prefix=\"fn\" uri=\"http://java.sun.com/jsp/jstl/functions\" %>\n    <c:out value=\"${fn:trim('{world}')}\"/>\n\nWhen running with Security Manager I observe three different behaviors:\n\nA). The proper error report from bug 48112\n(..)\norg.apache.el.parser.ParseException: Encountered \" <ILLEGAL_CHARACTER> \"\\' \"\"\nat line 1, column 11.\n(..)\n\nTo reproduce:\n1. Clear the working directory\n2. Start Tomcat\n3. Remove added lines from basic-arithmetic.jsp, so that it becomes valid\n4. Browse http://localhost:8080/examples/jsp/jsp2/el/basic-arithmetic.jsp\n5. Add the lines to basic-arithmetic.jsp\n6. Reload the page in the browser\n7. Observe the error\n\nB). AccessControlException\n\nTo reproduce:\n1. Clear the working directory\n2. Start Tomcat\n3. Add the lines to basic-arithmetic.jsp\n4. Browse http://localhost:8080/examples/jsp/jsp2/el/basic-arithmetic.jsp\n5. Observe the error\n\nC). NoClassDefFoundError\n\nTo reproduce:\n1. Run A) or B)\n2. Stop Tomcat and do *not* clear the working directory\n3. Start Tomcat\n4. Browse http://localhost:8080/examples/jsp/jsp2/el/basic-arithmetic.jsp\n5. Observe the error\n\n\njava.lang.NoClassDefFoundError: Could not initialize class org.apache.jsp.jsp.jsp2.el.basic_002darithmetic_jsp\n\tsun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)\n\tsun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)\n\tsun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)\n\tjava.lang.reflect.Constructor.newInstance(Unknown Source)\n\tjava.lang.Class.newInstance0(Unknown Source)\n\tjava.lang.Class.newInstance(Unknown Source)\n\torg.apache.jasper.servlet.JspServletWrapper.getServlet(JspServletWrapper.java:145)\n\nI observe the following oddity:\n1. Run B)\n2. In the working folder both java and class file for the page are present:\nbasic_002darithmetic_jsp.class\nbasic_002darithmetic_jsp.java\n\nSo, how does it produce a class file when java file generation should have failed with an exception?", "id": 133087, "time": "2009-12-23T06:01:26Z", "bug_id": 48438, "creation_time": "2009-12-23T06:01:26Z", "is_private": false, "attachment_id": null}, {"count": 3, "tags": [], "creator": "knst.kolinko@gmail.com", "text": "Created attachment 24755\nlocalhost.2009-12-23.log for Comment 2", "id": 133088, "time": "2009-12-23T06:08:21Z", "bug_id": 48438, "creation_time": "2009-12-23T06:08:21Z", "is_private": false, "attachment_id": 24755}, {"count": 4, "tags": [], "creator": "knst.kolinko@gmail.com", "attachment_id": null, "id": 133089, "time": "2009-12-23T06:15:23Z", "bug_id": 48438, "creation_time": "2009-12-23T06:15:23Z", "is_private": false, "text": "Additional observation for A):\n\nThat org.apache.el.parser.ParseException: occurs at run time, not at compile time!\n\nIt explains why the class file is generated.\n\nYou can see the stacktrace for this case in attachment 24755.\n\nIt is\n at org.apache.el.parser.ELParser.generateParseException(ELParser.java:2142)\n at org.apache.el.parser.ELParser.jj_consume_token(ELParser.java:2024)\n (.. a dozen of ELParser methods)\n (.. a pair of ExpressionBuilder methods)\n at org.apache.el.ExpressionFactoryImpl.createValueExpression(ExpressionFactoryImpl.java:68)\n at org.apache.jasper.runtime.PageContextImpl$13.run(PageContextImpl.java:919)\n at java.security.AccessController.doPrivileged(Native Method)\n at org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate(PageContextImpl.java:913)\n at org.apache.jsp.jsp.jsp2.el.basic_002darithmetic_jsp._jspx_meth_c_005fout_005f0(basic_002darithmetic_jsp.java:205)\n at org.apache.jsp.jsp.jsp2.el.basic_002darithmetic_jsp._jspService(basic_002darithmetic_jsp.java:179)\n\nSo it occurs in _jspService() of a running page, when it calls PageContextImpl.proprietaryEvaluate to evaluate an EL expression."}, {"count": 5, "tags": [], "creator": "knst.kolinko@gmail.com", "attachment_id": null, "id": 133736, "time": "2010-01-20T12:02:34Z", "bug_id": 48438, "creation_time": "2010-01-20T12:02:34Z", "is_private": false, "text": "It is a duplicate of bug 48580.\n\nThat this page would fail without SecurityManager is just a coincidence.\nWith a SecurityManager it does not initialize (fails in its <clinit>), and that happens earlier than any EL evaluation takes place.\n\n*** This bug has been marked as a duplicate of bug 48580 ***"}]