[{"count": 0, "attachment_id": 25668, "bug_id": 49529, "is_private": false, "id": 138032, "time": "2010-06-30T08:56:29Z", "creator": "olivier.masseau@ic.lu", "creation_time": "2010-06-30T08:56:29Z", "tags": [], "text": "Created attachment 25668\nExcel workbook used to reproduce the bug.\n\nIf I open an existing workbook with one sheet and then create a drawing patriarch for the sheet, I cannot clone the sheet anymore.\n\nSimple code to reproduce the bug :\n\npublic static void main(String[] args) {\n\t\ttry {\n\t\t\t\n\t\t\tWorkbook workbook = WorkbookFactory.create(new FileInputStream(\"C:\\\\test.xls\"));\n\t\t\tworkbook.getSheetAt(0).createDrawingPatriarch();\n\t\t\tworkbook.cloneSheet(0);\n\t\t\tSystem.out.println(\"OK\");\n\t\t}\n\t\tcatch(Exception e) {\n\t\t\te.printStackTrace();\n\t\t}\n\t}\n\nIt produces this exception :\n\njava.lang.IllegalStateException: EOF - next record not available\n\tat org.apache.poi.hssf.record.RecordInputStream.nextRecord(RecordInputStream.java:190)\n\tat org.apache.poi.hssf.record.Record.cloneViaReserialise(Record.java:88)\n\tat org.apache.poi.hssf.record.AbstractEscherHolderRecord.clone(AbstractEscherHolderRecord.java:150)\n\tat org.apache.poi.hssf.model.Sheet.cloneSheet(Sheet.java:375)\n\tat org.apache.poi.hssf.usermodel.HSSFSheet.cloneSheet(HSSFSheet.java:121)\n\tat org.apache.poi.hssf.usermodel.HSSFWorkbook.cloneSheet(HSSFWorkbook.java:662)\n\tat org.apache.poi.hssf.usermodel.HSSFWorkbook.cloneSheet(HSSFWorkbook.java:87)"}, {"count": 1, "tags": [], "bug_id": 49529, "text": "Created attachment 28512\nFixed bug with cloning empty EscherAggregate records\n\nBug appears only if sheet has no drawing records. If we try to serialize empty EscherRecord it returns empty bytes array what can cause exceptions.", "id": 155325, "time": "2012-03-27T20:52:14Z", "creator": "superrubiroyd@gmail.com", "creation_time": "2012-03-27T20:52:14Z", "is_private": false, "attachment_id": 28512}, {"count": 2, "tags": [], "creator": "yegor@dinom.ru", "attachment_id": null, "is_private": false, "id": 155358, "time": "2012-03-29T10:36:36Z", "bug_id": 49529, "creation_time": "2012-03-29T10:36:36Z", "text": "Thanks for the patch, applied in r1306781 along with a unit test. The attached sample was included in our collection of test files.\n\nYegor"}]