[{"count": 0, "tags": [], "text": "Created attachment 28357\nFailing document\n\nThe attached document fails to open in POI 3.7.  From a cursory look in the debugger where the IllegalStateException is being thrown, it looks to me like this can be safely ignored since it's an unused reference.  (As an aside, it would be much more polite to your callers to use a checked exception so they'd know it was coming and be able to handle it.)\n\nThe stack trace is:\n\njava.lang.IllegalStateException: A sheet hyperlink must either have a location, or a relationship. Found:\n<xml-fragment ref=\"A1\" tooltip=\"Sort on ID\" display=\"ID\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\" xmlns:mc=\"http://schemas.openxmlformats.org/markup-compatibility/2006\" xmlns:x14ac=\"http://schemas.microsoft.com/office/spreadsheetml/2009/9/ac\"/>\n\tat org.apache.poi.xssf.usermodel.XSSFHyperlink.<init>(XSSFHyperlink.java:72)\n\tat org.apache.poi.xssf.usermodel.XSSFSheet.initHyperlinks(XSSFSheet.java:205)\n\tat org.apache.poi.xssf.usermodel.XSSFSheet.read(XSSFSheet.java:159)\n\tat org.apache.poi.xssf.usermodel.XSSFSheet.onDocumentRead(XSSFSheet.java:134)\n\tat org.apache.poi.xssf.usermodel.XSSFWorkbook.onDocumentRead(XSSFWorkbook.java:235)\n\tat org.apache.poi.POIXMLDocument.load(POIXMLDocument.java:190)\n\tat org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:189)", "is_private": false, "bug_id": 52716, "id": 153957, "time": "2012-02-20T18:38:29Z", "creator": "tfmorris@gmail.com", "creation_time": "2012-02-20T18:38:29Z", "attachment_id": 28357}, {"count": 1, "tags": [], "creator": "apache@gagravarr.org", "attachment_id": null, "id": 153958, "time": "2012-02-20T18:41:53Z", "bug_id": 52716, "creation_time": "2012-02-20T18:41:53Z", "is_private": false, "text": "Have you tried with POI 3.8 beta 5?"}, {"count": 2, "tags": [], "creator": "tfmorris@gmail.com", "attachment_id": null, "id": 153961, "time": "2012-02-21T04:39:55Z", "bug_id": 52716, "creation_time": "2012-02-21T04:39:55Z", "is_private": false, "text": "The behavior is the same with 3.8b5.  It doesn't look like the code has changed at all in this area.  Which bug fix did you think was in beta 5 that would improve this?"}, {"text": "The user who provided the file reports that it was created in the following manner: \n\n\"The file was created by dumping an mSQL database (by Hughes) to an HTML page using a simple table. The HTML table was dragged and dropped to Excel 2010.\"", "tags": [], "bug_id": 52716, "is_private": false, "count": 3, "id": 154003, "time": "2012-02-21T19:45:09Z", "creator": "tfmorris@gmail.com", "creation_time": "2012-02-21T19:45:09Z", "attachment_id": null}, {"text": "Should be fixed in r1292295, junit added.\n\n>  (As an aside, it\n> would be much more polite to your callers to use a checked exception so they'd\n> know it was coming and be able to handle it.)\n> \n\nThe only checked exception that can be thrown when constructing XSSFWorkbook is IOException but it is not the case. So we stay with IllegalStateException.\n\nYegor", "tags": [], "bug_id": 52716, "is_private": false, "count": 4, "id": 154030, "time": "2012-02-22T14:15:25Z", "creator": "yegor@dinom.ru", "creation_time": "2012-02-22T14:15:25Z", "attachment_id": null}, {"count": 5, "tags": [], "creator": "tfmorris@gmail.com", "attachment_id": null, "id": 154661, "time": "2012-03-07T23:35:03Z", "bug_id": 52716, "creation_time": "2012-03-07T23:35:03Z", "is_private": false, "text": "Thanks for the quick fix.  I verified the fix in SVN and it works great.\n\nIs there a projected date when 3.8 will be released?  I looked at the web site and checked the dev list mail archive and wasn't able to figure out what the schedule is.\n\nThanks again!"}, {"count": 6, "tags": [], "creator": "yegor@dinom.ru", "attachment_id": null, "text": "> \n> Is there a projected date when 3.8 will be released?  I looked at the web site\n> and checked the dev list mail archive and wasn't able to figure out what the\n> schedule is.\n> \n\nI was planning to roll 3.8-beta6 in March and then release 3.8-final sometime in mid or late April, but there is a good chance we will skip beta6 and release 3.8-final within a month. \n\nStay on poi-dev, the release date will be discussed.\n\n\nYegor", "id": 154672, "time": "2012-03-08T05:12:38Z", "bug_id": 52716, "creation_time": "2012-03-08T05:12:38Z", "is_private": false}, {"count": 7, "tags": [], "text": "I'm reopening the bug (having the same with 3.11):\n\njava.lang.Class - java.lang.IllegalStateException: A sheet hyperlink must either have a location, or a relationship. Found:\n<xml-fragment ref=\"B3\" display=\"Something\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\" xmlns:mc=\"http://schemas.openxmlformats.org/markup-compatibility/2006\" xmlns:x14ac=\"http://schemas.microsoft.com/office/spreadsheetml/2009/9/ac\"/>\n\tat org.apache.poi.xssf.usermodel.XSSFHyperlink.<init>(XSSFHyperlink.java:72)\n\tat org.apache.poi.xssf.usermodel.XSSFSheet.initHyperlinks(XSSFSheet.java:205)\n\tat org.apache.poi.xssf.usermodel.XSSFSheet.read(XSSFSheet.java:159)\n\tat org.apache.poi.xssf.usermodel.XSSFSheet.onDocumentRead(XSSFSheet.java:134)\n\tat org.apache.poi.xssf.usermodel.XSSFWorkbook.onDocumentRead(XSSFWorkbook.java:235)\n\tat org.apache.poi.POIXMLDocument.load(POIXMLDocument.java:190)\n\tat org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:182)\n\tat org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:63)\n\tat org.is.jxlpoi.JXLPOIWorkbook.getWorkbook(JXLPOIWorkbook.java:80)", "is_private": false, "bug_id": 52716, "id": 181058, "time": "2015-02-13T17:53:01Z", "creator": "gavr145@gmail.com", "creation_time": "2015-02-13T17:53:01Z", "attachment_id": null}, {"text": "Please provide a sample document (unless it can be reproduced with the one attached here as well).", "tags": [], "bug_id": 52716, "is_private": false, "count": 8, "id": 181068, "time": "2015-02-13T20:43:17Z", "creator": "dominik.stadler@gmx.at", "creation_time": "2015-02-13T20:43:17Z", "attachment_id": null}, {"count": 9, "tags": [], "text": "Yes, it is reproducable with the attached document (mfb_a.xlsx):\n\n\n\njava.lang.IllegalStateException: A sheet hyperlink must either have a location, or a relationship. Found:\n<xml-fragment ref=\"A1\" tooltip=\"Sort on ID\" display=\"ID\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\" xmlns:mc=\"http://schemas.openxmlformats.org/markup-compatibility/2006\" xmlns:x14ac=\"http://schemas.microsoft.com/office/spreadsheetml/2009/9/ac\"/>\n\tat org.apache.poi.xssf.usermodel.XSSFHyperlink.<init>(XSSFHyperlink.java:72)\n\tat org.apache.poi.xssf.usermodel.XSSFSheet.initHyperlinks(XSSFSheet.java:205)\n\tat org.apache.poi.xssf.usermodel.XSSFSheet.read(XSSFSheet.java:159)\n\tat org.apache.poi.xssf.usermodel.XSSFSheet.onDocumentRead(XSSFSheet.java:134)\n\tat org.apache.poi.xssf.usermodel.XSSFWorkbook.onDocumentRead(XSSFWorkbook.java:235)\n\tat org.apache.poi.POIXMLDocument.load(POIXMLDocument.java:190)\n\tat org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:182)\n\tat org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:63)", "is_private": false, "bug_id": 52716, "id": 181141, "time": "2015-02-18T15:03:41Z", "creator": "gavr145@gmail.com", "creation_time": "2015-02-18T15:03:41Z", "attachment_id": null}, {"text": "I mean, with the file attached by the previous reporter, the originally submitted file.", "tags": [], "bug_id": 52716, "is_private": false, "count": 10, "id": 181142, "time": "2015-02-18T15:14:08Z", "creator": "gavr145@gmail.com", "creation_time": "2015-02-18T15:14:08Z", "attachment_id": null}, {"text": "Hm, there is an active unit-test at TestXSSFHyperlink.test52716() which verifies that this file can still be read correctly. I also tried with WorkbookFactory and it did also work fine.\n\nAre you sure you are using the latest version of POI? If so, please share your code to see if there is any difference in how you load the workbook.", "tags": [], "bug_id": 52716, "is_private": false, "count": 11, "id": 181231, "time": "2015-02-21T11:10:09Z", "creator": "dominik.stadler@gmx.at", "creation_time": "2015-02-21T11:10:09Z", "attachment_id": null}, {"text": "Hi Dominik,\n\nThis particular exception occurs with poi-3.11-FINAL as noted above, i.e. the latest stable version (we were not thinking to put beta to production yet and haven't tested the beta yet), not the latest version from svn.\n\nThe WorkbookFactory is used:\n\t\t\t\n\tFileInputStream fis = new FileInputStream(\"C:/AAA/mfb_a.xlsx\");\n\tWorkbook temp = WorkbookFactory.create(fis);\n\nwith both your file (I just double-checked it) and our file, with the same exception.\n\nDue to this thread, I thought that this issue was fixed long before 3.11-FINAL. \n\nPlease let me know if you want more information.\n\nThanks", "tags": [], "bug_id": 52716, "is_private": false, "count": 12, "id": 181260, "time": "2015-02-23T14:45:48Z", "creator": "gavr145@gmail.com", "creation_time": "2015-02-23T14:45:48Z", "attachment_id": null}, {"count": 13, "tags": [], "creator": "dominik.stadler@gmx.at", "attachment_id": null, "id": 181278, "time": "2015-02-23T21:06:30Z", "bug_id": 52716, "creation_time": "2015-02-23T21:06:30Z", "is_private": false, "text": "It is fixed since somewhere around 2012 as far as I see.\n\nSo if I look at line \"72\" of class XSSFHyperlink which is referenced in the exception stacktrace that you posted, I see that since the fix in 2012 the line 72 is not executable code, but rather a bracket (\"}\"), so I conclude that if you are really seeing the same stacktrace, then you are likely still having some outdated version of POI in use somewhere, i.e. by having an old jar-file in the classpath. \n\nIn fact the error text that is shown in the exception does not even exist any more in all of POI's code since 2012, so I cannot see how it could even appear in a current version of POI.\n\nIf you really can reproduce this problem with version 3.11 of POI, then please post the actual stacktrace that you get so we can see what the actual error message is. The \"A sheet hyperlink must either ...\" is very unlikely to still be possible with 3.11 and newer..."}, {"count": 14, "tags": [], "bug_id": 52716, "is_private": false, "text": "Ok, here is my fault!\n\nI found a dependency from another imported project which used poi-3.7-20101029.jar.\nyou are right!\n\nThank you very much, at least this can be closed.", "id": 181279, "time": "2015-02-23T21:25:36Z", "creator": "gavr145@gmail.com", "creation_time": "2015-02-23T21:25:36Z", "attachment_id": null}]