[{"text": "Created attachment 29184\nSmall sample web app\n\nWhen a servlet adds enough information to a response exceed the maxHttpHeaderSize limitconfigured for an HTTP 1.1 connector, an ArrayIndexOutOfBoundsException is thrown by Tomcat (example stacktrace below), and the connection is closed without writing any data.\n\nIn a scenario like this, should a response with a status of 500 be returned to indicate a server error? (and perhaps the server should log a message indicating that the limit has been exceeded for a response, instead of throwing an ArrayIndexOutOfBoundsException?)\n\n\n\nThis issue can be reproduced by testing with a servlet that implements this contrived doGet method (sample application with this is attached):\n\n\tprotected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {\n\t\tchar[] bigBuffer = new char[1024 * 8];\n\t\tArrays.fill(bigBuffer, 'a');\n\t\tresponse.setHeader(\"x-example\", new String(bigBuffer));\n\t\t\n\t\tresponse.setContentType(\"text/plain\");\n\t\tresponse.setCharacterEncoding(\"ISO-8859-1\");\n\n\t\tWriter out = response.getWriter();\n\t\tout.write(\"Hello!\");\n\t\tout.close();\n\t}\n\n\nThis has been observed under the following configurations:\n\nTomcat 6.0.26/Oracle JDK 1.6.0_25 (64-bit)/SUSE Linux 10\nTomcat 6.0.35/Oracle JDK 1.7.0 (64-bit)/Windows 7\n\n- Tomcat is not running behind a web server in any of these configurations\n\n- The connector being used in both cases is Coyote HTTP/1.1\n\n\n\n\nStacktrace:\n\nAug 07, 2012 6:11:26 PM org.apache.catalina.core.StandardWrapperValve invoke\nSEVERE: Servlet.service() for servlet SampleServlet threw exception\njava.lang.ArrayIndexOutOfBoundsException: 8192\n\tat org.apache.coyote.http11.InternalOutputBuffer.write(InternalOutputBuffer.java:730)\n\tat org.apache.coyote.http11.InternalOutputBuffer.write(InternalOutputBuffer.java:641)\n\tat org.apache.coyote.http11.InternalOutputBuffer.sendHeader(InternalOutputBuffer.java:514)\n\tat org.apache.coyote.http11.Http11Processor.prepareResponse(Http11Processor.java:1637)\n\tat org.apache.coyote.http11.Http11Processor.action(Http11Processor.java:956)\n\tat org.apache.coyote.Response.action(Response.java:183)\n\tat org.apache.coyote.Response.sendHeaders(Response.java:379)\n\tat org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:314)\n\tat org.apache.catalina.connector.OutputBuffer.close(OutputBuffer.java:274)\n\tat org.apache.catalina.connector.CoyoteWriter.close(CoyoteWriter.java:108)\n\tat com.example.SampleServlet.doGet(SampleServlet.java:36)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:617)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:717)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)\n\tat org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)\n\tat org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)\n\tat org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)\n\tat org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)\n\tat org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)\n\tat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)\n\tat org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:859)\n\tat org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:602)\n\tat org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)\n\tat java.lang.Thread.run(Unknown Source)\n\nAug 07, 2012 6:11:26 PM org.apache.catalina.core.StandardWrapperValve invoke\nSEVERE: Servlet.service() for servlet SampleServlet threw exception\njava.lang.ArrayIndexOutOfBoundsException: 8192\n\tat org.apache.coyote.http11.InternalOutputBuffer.write(InternalOutputBuffer.java:730)\n\tat org.apache.coyote.http11.InternalOutputBuffer.write(InternalOutputBuffer.java:641)\n\tat org.apache.coyote.http11.InternalOutputBuffer.sendHeader(InternalOutputBuffer.java:514)\n\tat org.apache.coyote.http11.Http11Processor.prepareResponse(Http11Processor.java:1637)\n\tat org.apache.coyote.http11.Http11Processor.action(Http11Processor.java:956)\n\tat org.apache.coyote.Response.action(Response.java:183)\n\tat org.apache.coyote.Response.sendHeaders(Response.java:379)\n\tat org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:314)\n\tat org.apache.catalina.connector.OutputBuffer.close(OutputBuffer.java:274)\n\tat org.apache.catalina.connector.CoyoteWriter.close(CoyoteWriter.java:108)\n\tat com.example.SampleServlet.doGet(SampleServlet.java:36)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:617)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:717)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)\n\tat org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)\n\tat org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)\n\tat org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)\n\tat org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)\n\tat org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)\n\tat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)\n\tat org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:859)\n\tat org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:602)\n\tat org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)\n\tat java.lang.Thread.run(Unknown Source)\n\nAug 07, 2012 6:11:26 PM org.apache.coyote.http11.Http11Processor process\nSEVERE: Error processing request\njava.lang.ArrayIndexOutOfBoundsException\n\tat java.lang.System.arraycopy(Native Method)\n\tat org.apache.coyote.http11.InternalOutputBuffer.write(InternalOutputBuffer.java:701)\n\tat org.apache.coyote.http11.InternalOutputBuffer.sendStatus(InternalOutputBuffer.java:438)\n\tat org.apache.coyote.http11.Http11Processor.prepareResponse(Http11Processor.java:1624)\n\tat org.apache.coyote.http11.Http11Processor.action(Http11Processor.java:956)\n\tat org.apache.coyote.Response.action(Response.java:183)\n\tat org.apache.coyote.Response.sendHeaders(Response.java:379)\n\tat org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:314)\n\tat org.apache.catalina.connector.OutputBuffer.close(OutputBuffer.java:274)\n\tat org.apache.catalina.connector.Response.finishResponse(Response.java:493)\n\tat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:317)\n\tat org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:859)\n\tat org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:602)\n\tat org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)\n\tat java.lang.Thread.run(Unknown Source)\n\nAug 07, 2012 6:11:26 PM org.apache.coyote.http11.Http11Processor process\nSEVERE: Error processing request\njava.lang.ArrayIndexOutOfBoundsException\n\tat java.lang.System.arraycopy(Native Method)\n\tat org.apache.coyote.http11.InternalOutputBuffer.write(InternalOutputBuffer.java:701)\n\tat org.apache.coyote.http11.InternalOutputBuffer.sendStatus(InternalOutputBuffer.java:438)\n\tat org.apache.coyote.http11.Http11Processor.prepareResponse(Http11Processor.java:1624)\n\tat org.apache.coyote.http11.Http11Processor.action(Http11Processor.java:956)\n\tat org.apache.coyote.Response.action(Response.java:183)\n\tat org.apache.coyote.Response.sendHeaders(Response.java:379)\n\tat org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:314)\n\tat org.apache.catalina.connector.OutputBuffer.close(OutputBuffer.java:274)\n\tat org.apache.catalina.connector.Response.finishResponse(Response.java:493)\n\tat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:317)\n\tat org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:859)\n\tat org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:602)\n\tat org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)\n\tat java.lang.Thread.run(Unknown Source)\n\nAug 07, 2012 6:11:26 PM org.apache.coyote.http11.Http11Processor process\nSEVERE: Error finishing response\njava.lang.ArrayIndexOutOfBoundsException\n\tat java.lang.System.arraycopy(Native Method)\n\tat org.apache.coyote.http11.InternalOutputBuffer.write(InternalOutputBuffer.java:701)\n\tat org.apache.coyote.http11.InternalOutputBuffer.sendStatus(InternalOutputBuffer.java:438)\n\tat org.apache.coyote.http11.Http11Processor.prepareResponse(Http11Processor.java:1624)\n\tat org.apache.coyote.http11.Http11Processor.action(Http11Processor.java:956)\n\tat org.apache.coyote.Response.action(Response.java:181)\n\tat org.apache.coyote.http11.InternalOutputBuffer.endRequest(InternalOutputBuffer.java:398)\n\tat org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:901)\n\tat org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:602)\n\tat org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)\n\tat java.lang.Thread.run(Unknown Source)\n\nAug 07, 2012 6:11:26 PM org.apache.coyote.http11.Http11Processor process\nSEVERE: Error finishing response\njava.lang.ArrayIndexOutOfBoundsException\n\tat java.lang.System.arraycopy(Native Method)\n\tat org.apache.coyote.http11.InternalOutputBuffer.write(InternalOutputBuffer.java:701)\n\tat org.apache.coyote.http11.InternalOutputBuffer.sendStatus(InternalOutputBuffer.java:438)\n\tat org.apache.coyote.http11.Http11Processor.prepareResponse(Http11Processor.java:1624)\n\tat org.apache.coyote.http11.Http11Processor.action(Http11Processor.java:956)\n\tat org.apache.coyote.Response.action(Response.java:181)\n\tat org.apache.coyote.http11.InternalOutputBuffer.endRequest(InternalOutputBuffer.java:398)\n\tat org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:901)\n\tat org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:602)\n\tat org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)\n\tat java.lang.Thread.run(Unknown Source)", "tags": [], "bug_id": 53677, "is_private": false, "count": 0, "id": 161164, "time": "2012-08-07T23:28:11Z", "creator": "dan8mx@gmail.com", "creation_time": "2012-08-07T23:28:11Z", "attachment_id": 29184}, {"count": 1, "tags": [], "creator": "markt@apache.org", "attachment_id": null, "id": 161857, "time": "2012-08-30T21:59:41Z", "bug_id": 53677, "creation_time": "2012-08-30T21:59:41Z", "is_private": false, "text": "Fixed in trunk and 7.0.x and will be included in 7.0.30 onwards.\n\nIt has not yet been proposed for back-port as due to the connector refactoring, a 6.0.x specific patch will be required."}, {"count": 2, "attachment_id": null, "creator": "markt@apache.org", "text": "Marking as fixed since this was fixed in 7.0.x.\n\nNote it was not back-ported to 6.0.x since 6.0.x reached end of life before anyone expressed an interest in back-porting the fix.", "id": 195775, "time": "2017-01-01T11:13:26Z", "bug_id": 53677, "creation_time": "2017-01-01T11:13:26Z", "tags": [], "is_private": false}]