[{"count": 0, "text": "In rare cases, but reproducable on certain testsystems, I get the following stacktrace:\n\ncom.izforge.izpack.installer.InstallerException: The following error occurred while executing this line:\n/tmp/buildfile_resource7846034884221422628xml:7: The following error occurred while executing this line:\n/usr/local/app/bin/database_contents.xml:5: The following error occurred while executing this line:\nUnable to find jar:file:/usr/local/app/lib/ant/ant-contrib/1.0b3/ant-contrib.jar!/net/sf/antcontrib/antlib.xml\n        at com.izforge.izpack.event.AntActionInstallerListener.performAllActions(Unknown Source)\n        at com.izforge.izpack.event.AntActionInstallerListener.afterPacks(Unknown Source)\n        at com.izforge.izpack.installer.UnpackerBase.informListeners(Unknown Source)\n        at com.izforge.izpack.installer.Unpacker.run(Unknown Source)\n        at java.lang.Thread.run(Thread.java:736)\nCaused by: The following error occurred while executing this line:\n/tmp/buildfile_resource7846034884221422628xml:7: The following error occurred while executing this line:\n/usr/local/app/bin/database_contents.xml:5: The following error occurred while executing this line:\nUnable to find jar:file:/usr/local/app/lib/ant/ant-contrib/1.0b3/ant-contrib.jar!/net/sf/antcontrib/antlib.xml\n        at org.apache.tools.ant.ProjectHelper.addLocationToBuildException(ProjectHelper.java:551)\n        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:395)\n        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:48)\n        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)\n        at java.lang.reflect.Method.invoke(Method.java:600)\n        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)\n        at org.apache.tools.ant.Task.perform(Task.java:348)\n        at org.apache.tools.ant.Target.execute(Target.java:392)\n        at org.apache.tools.ant.Target.performTasks(Target.java:413)\n        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)\n        at org.apache.tools.ant.Project.executeTarget(Project.java:1368)\n        at com.izforge.izpack.event.AntAction.performAction(Unknown Source)\n        at com.izforge.izpack.event.AntAction.performInstallAction(Unknown Source)\n        ... 5 more\nCaused by: /tmp/buildfile_resource7846034884221422628xml:7: The following error occurred while executing this line:\n/usr/local/app/bin/database_contents.xml:5: The following error occurred while executing this line:\nUnable to find jar:file:/usr/local/app/lib/ant/ant-contrib/1.0b3/ant-contrib.jar!/net/sf/antcontrib/antlib.xml\n        at org.apache.tools.ant.ProjectHelper.addLocationToBuildException(ProjectHelper.java:551)\n        at org.apache.tools.ant.taskdefs.ImportTask.importResource(ImportTask.java:238)\n        at org.apache.tools.ant.taskdefs.ImportTask.execute(ImportTask.java:163)\n        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)\n        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:48)\n        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)\n        at java.lang.reflect.Method.invoke(Method.java:600)\n        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)\n        at org.apache.tools.ant.Task.perform(Task.java:348)\n        at org.apache.tools.ant.Target.execute(Target.java:392)\n        at org.apache.tools.ant.helper.ProjectHelper2.parse(ProjectHelper2.java:180)\n        at org.apache.tools.ant.ProjectHelper.configureProject(ProjectHelper.java:82)\n        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:393)\n        ... 17 more\nCaused by: /usr/local/app/bin/database_contents.xml:5: The following error occurred while executing this \nline:\nUnable to find jar:file:/usr/local/app/lib/ant/ant-contrib/1.0b3/ant-contrib.jar!/net/sf/antcontrib/antlib.xml\n        at org.apache.tools.ant.ProjectHelper.addLocationToBuildException(ProjectHelper.java:551)\n        at org.apache.tools.ant.taskdefs.Definer.loadAntlib(Definer.java:445)\n        at org.apache.tools.ant.taskdefs.Definer.execute(Definer.java:292)\n        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)\n        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:48)\n        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)\n        at java.lang.reflect.Method.invoke(Method.java:600)\n        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)\n        at org.apache.tools.ant.Task.perform(Task.java:348)\n        at org.apache.tools.ant.Target.execute(Target.java:392)\n        at org.apache.tools.ant.helper.ProjectHelper2.parse(ProjectHelper2.java:169)\n        at org.apache.tools.ant.taskdefs.ImportTask.importResource(ImportTask.java:229)\n        ... 29 more\nCaused by: Unable to find jar:file:/usr/local/app/lib/ant/ant-contrib/1.0b3/ant-contrib.jar!/net/sf/antcontrib/antlib.xml\n        at org.apache.tools.ant.taskdefs.Antlib.createAntlib(Antlib.java:68)\n        at org.apache.tools.ant.taskdefs.Definer.loadAntlib(Definer.java:440)\n        ... 40 more\nCaused by: java.io.FileNotFoundException: JAR entry net/sf/antcontrib/antlib.xml not found in /usr/local/app/lib/ant/ant-contrib/1.0b3/ant-contrib.jar\n        at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:125)\n        at org.apache.tools.ant.taskdefs.Antlib.createAntlib(Antlib.java:66)\n        ... 41 more\n\n\nin the definition:\n  <taskdef resource=\"net/sf/antcontrib/antlib.xml\">\n    <classpath>\n      <pathelement location=\"${install.prefix}/lib/ant/ant-contrib/1.0b3/ant-contrib.jar\"/>\n    </classpath>\n  </taskdef>\n\nThe File and the resource in it definitely exist.\nAnt 1.8.4 is used built-in here from an Izpack installer, but this doesn't play any role here, IMHO.\n\nThe important point is, that it fails just on the first try, but on the second on it suceeds, although there hasn't been changed anything on the appropriate location in between time.\n\nNote:\nAt the links\n- https://jira.springsource.org/browse/SPR-4639\n- http://stackoverflow.com/questions/1374438/disappearing-jar-entry-when-loading-using-spi\nI found some discussion about switching off caching in such cases for UrlConnection. Maybe this could be useful also for Ant.", "bug_id": 54473, "attachment_id": null, "id": 164825, "time": "2013-01-23T11:53:07Z", "creator": "renda.krell@gmail.com", "creation_time": "2013-01-23T11:53:07Z", "tags": [], "is_private": false}, {"count": 1, "tags": [], "creator": "renda.krell@gmail.com", "attachment_id": null, "is_private": false, "id": 164826, "time": "2013-01-23T11:56:32Z", "bug_id": 54473, "creation_time": "2013-01-23T11:56:32Z", "text": "OS, where this bug occurs:\nLinux 2.6.32.12-0.7-default #1 SMP 2010-05-20 11:14:20 +0200 x86_64 x86_64 x86_64 GNU/Linux"}, {"count": 2, "tags": [], "text": "JRE, which this bug occurs with:\n- Oracle JRE 6u38, Linux 64 bit\n- IBM J9 VM (build 2.4, JRE 1.6.0 IBM J9 2.4 Linux amd64-64 jvmxa6460sr7-20091214_49398 (JIT enabled, AOT enabled)", "attachment_id": null, "bug_id": 54473, "id": 164827, "time": "2013-01-23T11:58:24Z", "creator": "renda.krell@gmail.com", "creation_time": "2013-01-23T11:58:24Z", "is_private": false}, {"count": 3, "tags": [], "creator": "antoine@apache.org", "attachment_id": 29888, "id": 164860, "time": "2013-01-24T04:33:25Z", "bug_id": 54473, "creation_time": "2013-01-24T04:33:25Z", "is_private": false, "text": "Created attachment 29888\npatch for ProjectHelper2\n\nsuggested patch based on the information in the bug report"}, {"count": 4, "tags": [], "text": "Created attachment 29889\nPatch for the ANT_18_BRANCH\n\nHere is another patch for the Ant 1.8 branch which solves the problem for me. Are you able to apply this? Thanks", "attachment_id": 29889, "bug_id": 54473, "id": 164861, "time": "2013-01-24T06:48:15Z", "creator": "renda.krell@gmail.com", "creation_time": "2013-01-24T06:48:15Z", "is_private": false}, {"count": 5, "tags": [], "bug_id": 54473, "is_private": false, "text": "I've combined both patches and also fixed some other places that looked suspicious.\n\nsvn revision 1554684", "id": 172007, "time": "2014-01-01T21:56:02Z", "creator": "bodewig@apache.org", "creation_time": "2014-01-01T21:56:02Z", "attachment_id": null}, {"count": 6, "tags": [], "creator": "bodewig@apache.org", "attachment_id": null, "id": 172043, "time": "2014-01-02T16:06:30Z", "bug_id": 54473, "creation_time": "2014-01-02T16:06:30Z", "is_private": false, "text": "amended with revision 1554840"}, {"count": 7, "tags": [], "creator": "renda.krell@gmail.com", "attachment_id": null, "is_private": false, "id": 174134, "time": "2014-03-27T16:37:48Z", "bug_id": 54473, "creation_time": "2014-03-27T16:37:48Z", "text": "Would appreciate a release with this fix, this still occurs in 1.9.3 for me."}, {"count": 8, "text": "let's discuss a schedule for the next release on the user list", "bug_id": 54473, "is_private": false, "id": 174182, "time": "2014-03-30T23:42:42Z", "creator": "antoine@apache.org", "creation_time": "2014-03-30T23:42:42Z", "tags": [], "attachment_id": null}, {"count": 9, "tags": [], "bug_id": 54473, "attachment_id": null, "text": "Unfortunately I got the reopen this for the following reason:\nThe most latest suggested patch didn't apply for me, the problem reoccurred. The is necessary to apply this patch for solving it: http://svn.apache.org/viewvc/ant/core/trunk/src/main/org/apache/tools/ant/taskdefs/Antlib.java?r1=1375571&r2=1554684&pathrev=1554840\nThus, using conn.setDefaultUseCaches(false), not just setUseCaches(false), for whatever reason.", "id": 174937, "time": "2014-04-30T08:47:39Z", "creator": "renda.krell@gmail.com", "creation_time": "2014-04-30T08:47:39Z", "is_private": false}]