[{"count": 0, "tags": [], "bug_id": 5797, "attachment_id": null, "text": "Tomcat:3.2.4, Java:JDK1.3.1_01, OS:Win2K.\n\nConnection with a Java Apps (arcims Administrator).\nno loss of data?, no fails?, only that : \n\n 2002-01-10 23:25:29 - Ctx(  ): Exception in: R(  +  + null) - java.lang.StringIn\ndexOutOfBoundsException: String index out of range: -1\n        at java.lang.String.substring(String.java:1525)\n        at org.apache.tomcat.request.DirHandler.doService(StaticInterceptor.java\n:561)\n        at org.apache.tomcat.core.Handler.service(Handler.java:287)\n        at org.apache.tomcat.core.ServletWrapper.service(ServletWrapper.java:372\n)\n        at org.apache.tomcat.core.ContextManager.internalService(ContextManager.\njava:806)\n        at org.apache.tomcat.core.ContextManager.service(ContextManager.java:752\n)\n        at org.apache.tomcat.service.http.HttpConnectionHandler.processConnectio\nn(HttpConnectionHandler.java:213)\n        at org.apache.tomcat.service.TcpWorkerThread.runIt(PoolTcpEndpoint.java:\n416)\n        at org.apache.tomcat.util.ThreadPool$ControlRunnable.run(ThreadPool.java\n:501)\n        at java.lang.Thread.run(Thread.java:484)", "id": 9535, "time": "2002-01-10T14:59:07Z", "creator": "based@free.fr", "creation_time": "2002-01-10T14:59:07Z", "is_private": false}, {"count": 1, "tags": [], "creator": "based@free.fr", "text": "Tomcat:3.2.4, Java:JDK1.3.1_01, OS:NT4.\n\nsame Exception. \nbut failure :unable to login with arcims Administrator (a GIS application from\nESRI company).\n\nUpgrading to Tomcat 3.3 fix it.", "id": 9580, "time": "2002-01-12T02:12:01Z", "bug_id": 5797, "creation_time": "2002-01-12T02:12:01Z", "is_private": false, "attachment_id": null}, {"count": 2, "tags": [], "creator": "sriramnrn@gmail.com", "text": "Marked as FIXED as per feedback give in the original bug reporter's own comment.", "id": 93436, "time": "2006-09-12T17:36:42Z", "bug_id": 5797, "creation_time": "2006-09-12T17:36:42Z", "is_private": false, "attachment_id": null}]