[{"count": 0, "tags": [], "creator": "ognjen.d.blagojevic@gmail.com", "attachment_id": null, "id": 183894, "creation_time": "2015-07-05T21:09:20Z", "time": "2015-07-05T21:09:20Z", "bug_id": 58104, "text": "While smoke testing APR connector with following config:\n             \n    <Connector port=\"83\" protocol=\"org.apache.coyote.http11.Http11AprProtocol\"\n               connectionTimeout=\"20000\"\n               redirectPort=\"8443\" />\n\nI get sporadic errors in my log files:\n\n\n05-Jul-2015 22:46:45.669 SEVERE [http-apr-83-exec-9] org.apache.coyote.http11.AbstractHttp11Processor.endRequest Error finishing response\n org.apache.tomcat.jni.Error: 20005: An invalid socket was returned\n\tat org.apache.tomcat.jni.Socket.sendbb(Native Method)\n\tat org.apache.coyote.http11.InternalAprOutputBuffer.writeToSocket(InternalAprOutputBuffer.java:287)\n\tat org.apache.coyote.http11.InternalAprOutputBuffer.writeToSocket(InternalAprOutputBuffer.java:244)\n\tat org.apache.coyote.http11.InternalAprOutputBuffer.flushBuffer(InternalAprOutputBuffer.java:213)\n\tat org.apache.coyote.http11.AbstractOutputBuffer.endRequest(AbstractOutputBuffer.java:378)\n\tat org.apache.coyote.http11.AbstractHttp11Processor.endRequest(AbstractHttp11Processor.java:1800)\n\tat org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1143)\n\tat org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)\n\tat org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2503)\n\tat org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2492)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)\n\tat org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\n\tat java.lang.Thread.run(Thread.java:745)\n\nI don't find anything suspicious in my tests or configuration.", "is_private": false}, {"count": 1, "tags": [], "creator": "chris@christopherschultz.net", "attachment_id": null, "text": "I'm glad those native checks are starting to catch some errors and stop the JVM from crashing. Any chance this is reproducible? I'd love to get some of these socket errors in the APR connector found and fixed.", "id": 183898, "time": "2015-07-06T03:21:38Z", "bug_id": 58104, "creation_time": "2015-07-06T03:21:38Z", "is_private": false}, {"count": 2, "tags": [], "bug_id": 58104, "text": "Steps to reproduce:\n\n1. Install tcnative 1.1.33\n2. Download Tomcat 8.0.24 (.zip)\n3. Unpack\n4. Add APR connector config as described above\n5. Start Tomcat\n6. Use provided Java test class. It will crawl all pages (except websocket, manager, etc), looking for URLs, and then it will fetch all found pages 5 times. When it finishes, don't stop Tomcat yet. After some time (~20s, errors start to apear in the console.\n\nConfig details:\n\n06-Jul-2015 22:57:10.941 INFO [main] org.apache.catalina.startup.VersionLoggerLi\nstener.log Server version:        Apache Tomcat/8.0.24\n06-Jul-2015 22:57:10.943 INFO [main] org.apache.catalina.startup.VersionLoggerLi\nstener.log Server built:          Jul 1 2015 20:19:55 UTC\n06-Jul-2015 22:57:10.943 INFO [main] org.apache.catalina.startup.VersionLoggerLi\nstener.log Server number:         8.0.24.0\n06-Jul-2015 22:57:10.943 INFO [main] org.apache.catalina.startup.VersionLoggerLi\nstener.log OS Name:               Windows 7\n06-Jul-2015 22:57:10.944 INFO [main] org.apache.catalina.startup.VersionLoggerLi\nstener.log OS Version:            6.1\n06-Jul-2015 22:57:10.944 INFO [main] org.apache.catalina.startup.VersionLoggerLi\nstener.log Architecture:          amd64\n06-Jul-2015 22:57:10.944 INFO [main] org.apache.catalina.startup.VersionLoggerLi\nstener.log Java Home:             C:\\Program Files\\Java\\jdk1.7.0_79\\jre\n06-Jul-2015 22:57:10.944 INFO [main] org.apache.catalina.startup.VersionLoggerLi\nstener.log JVM Version:           1.7.0_79-b15\n06-Jul-2015 22:57:10.945 INFO [main] org.apache.catalina.startup.VersionLoggerLi\nstener.log JVM Vendor:            Oracle Corporation\n...\n06-Jul-2015 22:57:10.951 INFO [main] org.apache.catalina.core.AprLifecycleListen\ner.lifecycleEvent Loaded APR based Apache Tomcat Native library 1.1.33 using APR\n version 1.5.1.\n06-Jul-2015 22:57:10.952 INFO [main] org.apache.catalina.core.AprLifecycleListen\ner.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters\n [false], random [true].\n06-Jul-2015 22:57:11.773 INFO [main] org.apache.catalina.core.AprLifecycleListen\ner.initializeSSL OpenSSL successfully initialized (OpenSSL 1.0.1m 19 Mar 2015)\n06-Jul-2015 22:57:11.927 INFO [main] org.apache.coyote.AbstractProtocol.init Ini\ntializing ProtocolHandler [\"http-apr-83\"]\n...", "id": 183914, "time": "2015-07-06T21:04:58Z", "creator": "ognjen.d.blagojevic@gmail.com", "creation_time": "2015-07-06T21:04:58Z", "is_private": false, "attachment_id": null}, {"count": 3, "tags": [], "creator": "ognjen.d.blagojevic@gmail.com", "attachment_id": 32885, "text": "Created attachment 32885\nJava class to reproduce the problem.", "id": 183915, "time": "2015-07-06T21:06:27Z", "bug_id": 58104, "creation_time": "2015-07-06T21:06:27Z", "is_private": false}, {"count": 4, "tags": [], "bug_id": 58104, "text": "Hi,\n\nI checked that in more details and it appeared that the exception in the original report is not the root cause.\n\norg.apache.coyote.http11.AbstractHttp11Processor.process(SocketWrapper<S>)\n\nrow 1031 -> IOException\nrow 1038 -> Throwable and in this block an http access log without information is created (bug 58105)\n\nHere are the stack traces:\n\norg.apache.tomcat.jni.Error: 20005: An invalid socket was returned\n        at org.apache.tomcat.jni.Socket.recvbb(Native Method)\n        at org.apache.coyote.http11.InternalAprInputBuffer.doReadSocket(InternalAprInputBuffer.java:631)\n        at org.apache.coyote.http11.InternalAprInputBuffer.fill(InternalAprInputBuffer.java:583)\n        at org.apache.coyote.http11.InternalAprInputBuffer.parseRequestLine(InternalAprInputBuffer.java:140)\n        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1005)\n        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)\n        at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2503)\n        at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2492)\n        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)\n        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)\n        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\n        at java.lang.Thread.run(Thread.java:745)\njava.io.IOException: Read failed with APR/native error code [730,038]\n        at org.apache.coyote.http11.InternalAprInputBuffer.fill(InternalAprInputBuffer.java:607)\n        at org.apache.coyote.http11.InternalAprInputBuffer.parseRequestLine(InternalAprInputBuffer.java:140)\n        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1005)\n        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)\n        at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2503)\n        at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2492)\n        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)\n        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)\n23-Jul-2015 00:13:22.649 INFO [http-apr-8080-exec-10] org.apache.coyote.http11.AbstractHttp11Processor.process Error parsing HTTP request header\n Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.\n        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\n        at java.lang.Thread.run(Thread.java:745)", "id": 184132, "time": "2015-07-22T21:29:15Z", "creator": "violetagg@apache.org", "creation_time": "2015-07-22T21:29:15Z", "is_private": false, "attachment_id": null}, {"count": 5, "tags": [], "bug_id": 58104, "text": "The test case from bug 58103#c7 can be used for this issue also.\nOnce it is executed I can see the same exceptions that I posted earlier.", "id": 184138, "time": "2015-07-23T07:39:29Z", "creator": "violetagg@apache.org", "creation_time": "2015-07-23T07:39:29Z", "is_private": false, "attachment_id": null}, {"count": 6, "tags": [], "bug_id": 58104, "text": "The root cause is the same as bug 58103. The only differences are in how the connectors behave once something has gone wrong.\n\n*** This bug has been marked as a duplicate of bug 58103 ***", "id": 184202, "time": "2015-07-28T13:55:34Z", "creator": "markt@apache.org", "creation_time": "2015-07-28T13:55:34Z", "is_private": false, "attachment_id": null}, {"count": 7, "tags": [], "creator": "ognjen.d.blagojevic@gmail.com", "attachment_id": null, "text": "Thank you.", "id": 184284, "time": "2015-08-03T12:42:53Z", "bug_id": 58104, "creation_time": "2015-08-03T12:42:53Z", "is_private": false}]