[{"count": 0, "tags": [], "bug_id": 58259, "attachment_id": null, "id": 184623, "time": "2015-08-18T15:20:45Z", "creator": "adnan_zafar@cable.comcast.com", "creation_time": "2015-08-18T15:20:45Z", "is_private": false, "text": "I can see this exception created in my log file from time to time. This bug has been reported before in several previous versions of Tomcat.\n\n\n17-Aug-2015 17:48:33.056 INFO [http-nio-8180-exec-120] org.apache.catalina.realm.JNDIRealm.authenticate Exception performing authentication. Retrying...\njavax.naming.CommunicationException [Root exception is java.net.SocketException: Connection reset]; remaining name 'DC=comcast,DC=com'\n    at com.sun.jndi.ldap.LdapClient.authenticate(LdapClient.java:162)\n    at com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2740)\n    at com.sun.jndi.ldap.LdapCtx.ensureOpen(LdapCtx.java:2648)\n    at com.sun.jndi.ldap.LdapCtx.ensureOpen(LdapCtx.java:2622)\n    at com.sun.jndi.ldap.LdapCtx.doSearch(LdapCtx.java:1942)\n    at com.sun.jndi.ldap.LdapCtx.searchAux(LdapCtx.java:1847)\n    at com.sun.jndi.ldap.LdapCtx.c_search(LdapCtx.java:1772)\n    at com.sun.jndi.toolkit.ctx.ComponentDirContext.p_search(ComponentDirContext.java:386)\n    at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(PartialCompositeDirContext.java:356)\n    at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(PartialCompositeDirContext.java:339)\n    at javax.naming.directory.InitialDirContext.search(InitialDirContext.java:267)\n    at org.apache.catalina.realm.JNDIRealm.getUserBySearch(JNDIRealm.java:1681)\n    at org.apache.catalina.realm.JNDIRealm.getUser(JNDIRealm.java:1517)\n    at org.apache.catalina.realm.JNDIRealm.getUser(JNDIRealm.java:1465)\n    at org.apache.catalina.realm.JNDIRealm.authenticate(JNDIRealm.java:1406)\n    at org.apache.catalina.realm.JNDIRealm.authenticate(JNDIRealm.java:1264)\n    at org.apache.catalina.realm.CombinedRealm.authenticate(CombinedRealm.java:192)\n    at org.apache.catalina.realm.LockOutRealm.authenticate(LockOutRealm.java:180)\n    at org.apache.catalina.authenticator.FormAuthenticator.authenticate(FormAuthenticator.java:245)\n    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:453)\n    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)\n    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)\n    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:617)\n    at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:240)\n    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)\n    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)\n    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)\n    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)\n    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1527)\n    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1484)\n    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)\n    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)\n    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\n    at java.lang.Thread.run(Thread.java:745)\nCaused by: java.net.SocketException: Connection reset\n    at java.net.SocketInputStream.read(SocketInputStream.java:196)\n    at java.net.SocketInputStream.read(SocketInputStream.java:122)\n    at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)\n    at java.io.BufferedInputStream.read1(BufferedInputStream.java:275)\n    at java.io.BufferedInputStream.read(BufferedInputStream.java:334)\n    at com.sun.jndi.ldap.Connection.run(Connection.java:853)\n    ... 1 more"}, {"count": 1, "tags": [], "bug_id": 58259, "attachment_id": null, "text": "Bugzilla is not a support forum. Please use the users mailing list.", "id": 184625, "time": "2015-08-18T15:31:54Z", "creator": "markt@apache.org", "creation_time": "2015-08-18T15:31:54Z", "is_private": false}, {"count": 2, "tags": [], "creator": "adnan_zafar@cable.comcast.com", "attachment_id": null, "text": "(In reply to Mark Thomas from comment #1)\n> Bugzilla is not a support forum. Please use the users mailing list.\n\nThis is a bug that has been reported in other versions of Tomcat. How is this considered a support request?", "id": 184626, "time": "2015-08-18T15:38:56Z", "bug_id": 58259, "creation_time": "2015-08-18T15:38:56Z", "is_private": false}]