[{"count": 0, "tags": [], "creator": "r.kohling@gmail.com", "text": "Hi\nGot this stacktrace with the coment \"Please raise a bug\". (The cause was my fault)\n\nMy processSheet(...) is asynchronous and the workbook had been closed from outside in the meantime. So you have to decide, if this is a bug or a PEBCAK problem.\n\norg.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Rule M2.4 exception : this error should NEVER happen! Please raise a bug at https://bz.apache.org/bugzilla/enter_bug.cgi?product=POI and attach a file that triggers it, thanks!\n\tat org.apache.poi.openxml4j.opc.internal.ContentTypeManager.getContentType(ContentTypeManager.java:343)\n\tat org.apache.poi.openxml4j.opc.internal.ContentTypeManager.removeContentType(ContentTypeManager.java:256)\n\tat org.apache.poi.openxml4j.opc.OPCPackage.removePart(OPCPackage.java:943)\n\tat org.apache.poi.openxml4j.opc.PackagePart.getOutputStream(PackagePart.java:522)\n\tat org.apache.poi.xssf.usermodel.XSSFWorkbook.commit(XSSFWorkbook.java:1678)\n\tat org.apache.poi.POIXMLDocumentPart.onSave(POIXMLDocumentPart.java:341)\n\tat org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:206)\n\tat com.dpd.geoRouting.testService.service.ExcelFileService.processSheet(ExcelFileService.java:241)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:606)\n\tat org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)\n\tat org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)\n\tat com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4786)\n\tat com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)\n\tat com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)\n\tat com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)\n\tat org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:55)\n\tat org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:606)\n\tat com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)\n\tat com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)\n\tat com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:369)\n\tat com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4758)\n\tat com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4746)\n\tat com.sun.ejb.containers.EjbAsyncTask.call(EjbAsyncTask.java:101)", "id": 190717, "time": "2016-05-04T09:28:10Z", "bug_id": 59427, "creation_time": "2016-05-04T09:28:10Z", "is_private": false, "attachment_id": null}, {"count": 1, "tags": [], "bug_id": 59427, "text": "I have updated the error message if you try to write a document that was already closed via r1744306, in a single-threaded app this cased an NullPointerException. \n\nI don't think we can do much more as POI does not guarantee thread-safety when one workbook is used in multiple threads concurrently.", "id": 191036, "time": "2016-05-17T19:09:48Z", "creator": "dominik.stadler@gmx.at", "creation_time": "2016-05-17T19:09:48Z", "is_private": false, "attachment_id": null}]